# Add to render.yaml
services:
  - type: web
    name: instagram-reel-processor
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        value: your_api_secret